### ISSUE TITLE
error when importing dcterms

### ISSUE THREAD

**Issue by wdduncan** [ontodev/robot#1075]
This issue is a follow up to https://github.com/INCATools/ontology-development-kit/issues/614. 

Suppose, you have an ODK file named `foo-odk.yaml` that references the `dcterms` library as an import group. E.g.:
```
import_group:
  products:
  - id: dcterms
      mirror_from: http://protege.stanford.edu/plugins/owl/dc/terms.owl
```

When you run `seed-via-docker.sh -C configs/foo-odk.yaml` you get the error:
```
ERROR OWLOntologyManagerImpl.checkForOntologyIDChange() new:Ontology(OntologyID(Anonymous-15)) [Axioms: 0 Logical Axioms: 0] First 20 axioms: {}
Could not load imported ontology: <http://protege.stanford.edu/plugins/owl/dc/terms.owl> Cause: Ontology already exists. OntologyID(OntologyIRI(<http://purl.org/dc/terms/>) VersionIRI(<null>))
```

@matentzn determined that the error has something to do with robot, and gave a work around. But, you may want to look into it.

This is how you can reproduce the error:
```
echo "INSERT DATA { <A> <B> <C> }" > q.sparql 
robot query -I http://protege.stanford.edu/plugins/owl/dc/terms.owl --update q.sparql merge -o tmp/test.ofn
```
