### ISSUE TITLE
New Operation: report

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#205]
ROBOT performs logical checks using `reason` and can run a custom suite of SPARQL queries using `verify`. Some repos successfully use this in combination with Makefiles and a custom suite of queries to implement robust checks in their pipeline (e.g. [GO](https://github.com/geneontology/go-ontology/tree/master/src/sparql); and also OSK).

We should make it easier for groups to do this out of the box. While customization is good, ROBOT should still provide an OBO-ish core set of queries and reports that could be used by OBO central for evaluation purposes. The groups could still customize and say for example "allow some classes to lack definitions".

In GO we are still very reliant on this script, it depends on obo format but it is a good model for a set of potential standard checks: https://github.com/geneontology/go-ontology/blob/master/src/util/check-obo-for-standard-release.pl

This could be implemented by robot distributing some sparql in its resources folder (or a standard obo place to fetch these) and/or procedural code (sometimes easier than sparql)

**Comment by cmungall** [comment]
Proposed name for this: `report`

the output product could be called a "report card"

**Comment by cmungall** [comment]
Should this command also produce standardized exports of things like tables of all classes and their labels, or is this overloading? Would that belong in `convert`?

**Comment by jamesaoverton** [comment]
I've used SPARQL for this. It's important to distinguish internal from external (imported) terms.

I'm fine with including this in `report`.

**Comment by cmungall** [comment]
Some suggestions on potential output. For checks, these could be treated as informative for now. Working with obo-ops and the obo community we could come up with varying levels of stringency. For some we can imagine different profiles, with the profile (e.g. obo-basic) declared in header.

general reporting

 * aggregate statistics
    * number/proportion of classes with textual definitions
    * number/proportion of classes with textual definitions that have/lack provenance
    * number/proportion of classes with owl definitions
    * number/proportion of classes with synonyms

checks

 * cardinality violations on annotation properties
    * rdfs:label
    * text defs
 * uniqueness
    * rdfs:label
    * text defs
    * exact syns+labels
 * logical checks
    * coherent (we get this from reason already but nice to bundle together)
    * no equivalent class pairs in main ontology
 * lexical checks (many can be `repair`ed)
    * trailing whitespace in literals
    * text defs first character capitalized
    * text defs end in `.` [OR: none end in `.`]
    * no illegal characters
    * most APs (label, syn, def) should never have newlines or formatting characters
    * CURIEs (e.g value of has_dbxref) should have declared prefix and be valid CURIEs
 * structural checks
    * deprecated classes should not be referenced in logical axioms
    * each non-root class should have minimally one superclass [released/reasoned version only]
 * ontology header
    * metadata complete
    * ontology IRI and versionIRI conform to standards
    * deprecated classes should have rdfs:label starting with 'obsolete'
 * style
     * classes with >1 subClassOf to named class (editor version only)

https://github.com/geneontology/go-ontology/blob/master/src/util/check-obo-for-standard-release.pl

**Comment by cmungall** [comment]
currently the GO reports give a lot of reference violations deep in the import chain. We know this is the case so would rather have an option to suppress reporting reference violations, @dougli1sqrd

**Comment by cmungall** [comment]
An example of how this is working (all on #231 at the moment).

Run report on an ontology:

```
$ robot report -i go-edit.obo -o report.yaml
ERROR REPORT FAILED! Violations: 18016
ERROR Severity 1 violations: 18006
ERROR Severity 2 violations: 10
ERROR Severity 3 violations: 0
ERROR Severity 4 violations: 0
ERROR Severity 5 violations: 0
```

@jamesaoverton - so far `-o` always means output *ontology*. Should we use a different arg, or stick with unix convention?

here is a sample of the report. We use the JSON subset of YAML so JSON is trivial too if you want the verbosity. It should also be easy to make nice HTML or Markdown from this, but this is a separate concern.

report is in sections, first reference issues:

````
problemsReport:
  invalidReferenceViolations:
  - axiom: "SubClassOf(<http://purl.obolibrary.org/obo/UBERON_0001343> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000067>\
      \ <http://purl.obolibrary.org/obo/GO_0007126>))"
    referencedObject: "<http://purl.obolibrary.org/obo/GO_0007126>"
    category: "DEPRECATED"
    type: "reference violation"
    description: "SubClassOf(<http://purl.obolibrary.org/obo/UBERON_0001343> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000067>\
      \ <http://purl.obolibrary.org/obo/GO_0007126>))"
    severity: 2
  - axiom: "DisjointUnion(Annotation(rdfs:comment \"Every biological process is either\
      \ a single-organism process or a multi-organism, but never both (GOC:mtg_obo_owl_Jan2013)\"\
      ) <http://purl.obolibrary.org/obo/GO_0008150> <http://purl.obolibrary.org/obo/GO_0044699>\
      \ <http://purl.obolibrary.org/obo/GO_0051704> )"
    referencedObject: "<http://purl.obolibrary.org/obo/GO_0044699>"
    category: "DEPRECATED"
    type: "reference violation"
    description: "DisjointUnion(Annotation(rdfs:comment \"Every biological process\
      \ is either a single-organism process or a multi-organism, but never both (GOC:mtg_obo_owl_Jan2013)\"\
      ) <http://purl.obolibrary.org/obo/GO_0008150> <http://purl.obolibrary.org/obo/GO_0044699>\
      \ <http://purl.obolibrary.org/obo/GO_0051704> )"
    severity: 2
```

next is ontology header issues. Bad GO! Lots of stuff missing from the header. Note that ontology header stuff is nice to do in SPARQL as we can do the same query across all ontologies in the triplestore, but a bit of redundancy is OK for convenience of user here:


```
  ontologyMetadataViolations:
  - description: "cardinality of dc:creator"
    severity: 1
    type: "ontology metadata violation"
  - description: "cardinality of dc:title"
    severity: 1
    type: "ontology metadata violation"
  - description: "cardinality of dc:description"
    severity: 1
    type: "ontology metadata violation"
```

then class metadata:

```
  classMetadataViolations:
  - description: "|<http://purl.obolibrary.org/obo/IAO_0000117>|=0 LESS_THAN 1"
    severity: 1
    cls: "<http://purl.obolibrary.org/obo/CHEBI_60941>"
    type: "class metadata violation"
...
  - description: "|rdfs:label|=0 LESS_THAN 1"
    severity: 1
    cls: "<http://purl.obolibrary.org/obo/GO_0005860>"
    type: "class metadata violation"
...
```

I think these are false positives, it should report dangling classes or deprecated classes

The YAML directly mirrors the simple POJO we have for the ReportCard, see java for details
