### ISSUE TITLE
New command: statistics/metrics (or add option to export/report)

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#627]
Was mentioned in a comment in #205 (now closed)

It would be useful to be able to generate aggregate stats in a standardized form in robot

This could include the axiom counts from as seen in Protege

![image](https://user-images.githubusercontent.com/50745/75079177-bbd36680-54bc-11ea-815a-0076f4f6baf0.png)

This would be useful for ontogeeks. But for others it would also be useful to see more basic stuff like

 - num classes/relations
    - incl/excl obsolete
    - all / main ID space only
 - num test definitions/synonyms/xrefs/other APs
 - num of existential restrictions broken down by OP
 - num of defining equivalence axioms (NamedC to AnonC)

A simple TSV would be best for most people, we could also consider an rdf export using vocabs like void/dcat

This could be a new command like `statistics` (Protege says "metrics" but this sounds like OBO evaluation, whereas these are just for informative purposes)

Or it could be piggy backed as an option on `report`. This is really more like a "report card" so not clear if aggregate stats figure here, and what category (INFO?) we would use.

**Comment by jamesaoverton** [comment]
Good idea. I prefer a new command (I like `statistics`), since this would have a different implementation and goals from `report`. But I could be convinced otherwise.

I don't have a pressing need for this, though. It would probably be a good feature for a new ROBOT contributor. Protege's implementation would be a starting point.

**Comment by cmungall** [comment]
Another option here is to add an option `--stats FILE` to `export` that will produce summary statistics and write these to FILE

The stats can be very basic. One line per header, listing total number of entries and number of distinct entries. E.g. if I specify `ID|label|synonym`

E.g.

```
ID count: 13000 13000
label count: 13000 13000
synonym count: 20000 17000
```

Anything more advances should be done using R/pandas/etc

I like this because it standardizes some of the summary stats we see published with ontologies. Sometimes I will see a table in a paper with headings like 'num relationships' or  'num terms' with ambiguous meaning. We have already thrashed out precise semantics of the column headings within export, including what should be done with anons etc.

**Comment by matentzn** [comment]
I would like to take this on! I would prefer `metrics` over `statistics`, because its broader, and I could include things like "owl profile", "serialisation format", which are not statistics.. I was thinking of something simple like this:

```
robot metrics -i ont.owl $(OPTS) -o metrics.yml
```

Which produces a file like this:

```
metrics:
  - metric: term_count
     metric_type: count
     value: 566 
  - metric: axiom_count
     metric_type: count
     value: 1000
  - metric: owl_profile
     metric_type: qualitative
     value: owl2_el
  - metric: synonym_count:
     metric_type: count
     value: 50
  - metric: referenced_namespaces_axioms
     metric_type: qualitative_count_list
     metric_value:
        - key: http://purl.obolibrary.org/obo/BSPO_
           value: 30
        - key: http://purl.obolibrary.org/obo/GO_
           value: 3000
   - metric: referenced_namespaces_terms
     metric_type: qualitative_count_list
     metric_value:
        - key: http://purl.obolibrary.org/obo/BSPO_
           value: 20
        - key: http://purl.obolibrary.org/obo/GO_
           value: 300
```

or

| metric | metric_value | metric_type |
| ---- | ---- | ---- | 
| term_count | 566 | count |
| axiom_count | 1000 | count |
| owl_profile | owl2_el | count |
| synonym_count | 50 | count |
| referenced_namespaces_terms | http://purl.obolibrary.org/obo/BSPO_\|30\|\|http://purl.obolibrary.org/obo/GO_\|3000 | qualitative_count_list |
| referenced_namespaces_axioms | http://purl.obolibrary.org/obo/BSPO_\|30\|\|http://purl.obolibrary.org/obo/GO_\|3000 | qualitative_count_list |

I have a lot of code doing this systematically; maybe its time to fold this into ROBOT. What do you think? Options I could see:

```
--use-base true
--basic-metrics true (simple structural metrics with counts)
-m metric (away to actually say: compute only this and that metric)
```

Let me know what you think. The need for metrics like `referenced_namespaces_axioms` came from @jamesaoverton and my current effort on the dashboard - so we need it. If people are against doing it here, I have to make another java jar doing exactly the above and add it to our pipelines - which I think is a waste.

**Comment by jamesaoverton** [comment]
If you prefer `metrics`, that's fine by me.

I don't like the `--use-base` option. The user should just specify the right file as the `--input`.

I would give output to tables higher priority than YAML. It would be good to have both.

I don't love all those pipes in the table. Why not multiple rows when needed?

| metric | metric_value | metric_type |
| ---- | ---- | ---- | 
| term_count | 566 | count |
| axiom_count | 1000 | count |
| owl_profile | owl2_el | count |
| synonym_count | 50 | count |
| referenced_namespaces_terms | http://purl.obolibrary.org/obo/BSPO_ 30 | qualitative_count_list |
| referenced_namespaces_terms | http://purl.obolibrary.org/obo/GO_ 3000 | qualitative_count_list |
| referenced_namespaces_axioms | http://purl.obolibrary.org/obo/BSPO_ 30 | qualitative_count_list |
| referenced_namespaces_axioms | http://purl.obolibrary.org/obo/GO_ 3000 | qualitative_count_list |

I guess all of these metrics will be implemented in Java?

**Comment by matentzn** [comment]
I agree with all you say (especially the `base` comment)! Happy with that table format instead, if it helps with readability!

Re java: yes! Actually, I have done all that already, I just need to figure out how to integrate into ROBOT.

**Comment by jamesaoverton** [comment]
How do you plan to use these metrics? Will you plot some/all of these metrics on some sort of dashboard? Will you have checks for thresholds or anomalies?

**Comment by matentzn** [comment]
I have a variety of use cases, one of which is simply mapping the evolution of an ontology across versions (axioms counts etc), another is (for the OBO dashboard) to extract the relevant information to determine the OBO score (axiom counts, namespace usage metrics in particular - this will answer the question of how much reuse was attempted, and how much an ontology is re-used)). 

I am thinking of even showing some very basic metrics on the OBO dashboard ontology page - at least to get a sense of how large/comprehensive an ontology is.

There were other use cases from which I moved on - ontology experiment frameworks like reasoner competitions like this stuff to do some prima facie binning of ontologies to explain performance, for example reasoning performance.

We can also use this to characterise the OBO foundry as a whole.

**Comment by cmungall** [comment]
not sure if it's too late to comment, but why the 'reification' in the output yaml?

E.g.

```yaml
metric: foo
metric_type: TYPE
value: VALUE
```

rather than the more direct

```yaml
foo: VALUE
```

with a separate data dictionary / json schema defining the keys (and in future the yaml could be json-ld-ified to make simple triples over clear data or object properties in OMO, redistributed optionally in ontology header)

**Comment by matentzn** [comment]
Oh sorry, I had fixed that a while ago.. Thats the new yaml:

```
+metrics:
  abox_axiom_count: 0
  abox_axiom_count_incl: 0
  abox_nominals: false
  abox_nominals_incl: false
  annotation_property_count: 38
  annotation_property_count_incl: 38
  assert_n_subclass_avg: 1.305084745762712
  assert_n_subclass_avg_incl: 1.305084745762712
  assert_n_superclass_avg: 1.326271186440678
  assert_n_superclass_avg_incl: 1.326271186440678
  ax_complexrhs_count: 464
  ax_complexrhs_count_incl: 464
  axiom_count: 5504
  axiom_count_incl: 5504
  axiom_length_max: 8
  axiom_length_max_incl: 8
  certain_cycle: true
  certain_cycle_incl: true
  class_count: 236
  class_count_incl: 236
  class_sgl_subcl_count: 41
  class_sgl_subcl_count_incl: 41
  dataproperty_count: 0
  dataproperty_count_incl: 0
  datatypes_count: 2
  datatypes_count_incl: 2
  dt_builtin_count: 2
  dt_builtin_count_incl: 2
  dt_notbuiltin_count: 0
  dt_notbuiltin_count_incl: 0
  expressivity: "SRIQ"
  expressivity_incl: "SRIQ"
  gci_count: 0
  gci_count_incl: 0
  gci_hidden_count: 105
  gci_hidden_count_incl: 105
  individual_count: 0
  individual_count_incl: 0
  instance_per_class_avg: 0.0
  instance_per_class_avg_incl: 0.0
  logical_axiom_count: 828
  logical_axiom_count_incl: 828
  most_freq_concept: "UBERON:0002091"
  most_freq_concept_incl: "UBERON:0002091"
  multiple_inheritance_count: 103
  multiple_inheritance_count_incl: 103
  named_supercl_count_max: 1
  named_supercl_count_max_incl: 1
  obj_property_count: 49
  obj_property_count_incl: 49
  ontology_anno_count: 0
  ontology_id: "http://purl.obolibrary.org/obo/uberon.owl"
  owl2: true
  owl2_dl: true
  owl2_el: false
  owl2_ql: false
  owl2_rl: false
  rbox_axiom_count: 56
  rbox_axiom_count_incl: 56
  rdfs: false
  rule_count: 0
  rule_count_incl: 0
  signature_entity_count: 325
  signature_entity_count_incl: 325
  syntax: "RDF/XML Syntax"
  tautology_count: 0
  tautology_count_incl: 0
  tbox_axiom_count: 772
  tbox_axiom_count_incl: 772
  tbox_nominals: false
  tbox_nominals_incl: false
  tboxrbox_axiom_count: 828
  tboxrbox_axiom_count_incl: 828
  undecl_entity_count: 5
  undecl_entity_count_incl: 5
  axiom_types:
  - "AnnotationAssertion"
  - "EquivalentClasses"
  - "TransitiveObjectProperty"
  - "SubObjectPropertyOf"
  - "SymmetricObjectProperty"
  - "SubPropertyChainOf"
  - "Declaration"
  - "SubClassOf"
  - "InverseObjectProperties"
  axiom_types_incl:
  - "AnnotationAssertion"
  - "EquivalentClasses"
  - "TransitiveObjectProperty"
  - "SubObjectPropertyOf"
  - "SymmetricObjectProperty"
  - "SubPropertyChainOf"
  - "Declaration"
  - "SubClassOf"
  - "InverseObjectProperties"
  constructs:
  - "Q"
  - "R"
  - "S"
  - "I"
  constructs_incl:
  - "Q"
  - "R"
  - "S"
  - "I"
  datatypes_builtin:
  - "XSD_STRING"
  - "XSD_ANY_URI"
  datatypes_builtin_incl:
  - "XSD_STRING"
  - "XSD_ANY_URI"
  datatypes_not_built_in: []
  datatypes_not_built_in_incl: []
  valid_imports: []
  valid_imports_incl: []
  axiom_type_count:
    AnnotationAssertion: 4356
    EquivalentClasses: 106
    TransitiveObjectProperty: 12
    SubObjectPropertyOf: 25
    SymmetricObjectProperty: 1
    SubPropertyChainOf: 11
    Declaration: 320
    SubClassOf: 666
    InverseObjectProperties: 7
  axiom_type_count_incl:
    AnnotationAssertion: 4356
    EquivalentClasses: 106
    TransitiveObjectProperty: 12
    SubObjectPropertyOf: 25
    SymmetricObjectProperty: 1
    SubPropertyChainOf: 11
    Declaration: 320
    SubClassOf: 666
    InverseObjectProperties: 7
  datatypes_axiom_count: {}
  datatypes_axiom_count_incl: {}
  namespace_axiom_count:
    oboInOwl: 4819
    IAO: 306
    UBERON: 1903
    rdfs: 308
    BFO: 283
    obo: 235
    RO: 307
    foaf: 56
    BSPO: 29
  namespace_axiom_count_incl:
    oboInOwl: 4819
    IAO: 306
    UBERON: 1903
    rdfs: 308
    BFO: 283
    obo: 235
    RO: 307
    foaf: 56
    BSPO: 29
  namespace_entity_count:
    oboInOwl: 20
    IAO: 3
    UBERON: 236
    xsd: 2
    BFO: 4
    rdfs: 3
    RO: 36
    obo: 13
    foaf: 1
    BSPO: 7
  namespace_entity_count_incl:
    oboInOwl: 20
    IAO: 3
    UBERON: 236
    xsd: 2
    BFO: 4
    rdfs: 3
    RO: 36
    obo: 13
    foaf: 1
    BSPO: 7
  owl2dl_profile_violation: {}
```
